### ISSUE TITLE
How to load the provided model parameter file?

### ISSUE THREAD

**Issue by Zhr1110** [BICLab/Spike-Driven-Transformer#10]
Hello, esteemed author,

Greetings. I am interested in migrating your model to another framework and have successfully downloaded the 6_512.pth.tar file you provided. May I inquire about the proper procedure for loading the model parameters into the framework?

Thank you for your guidance.

Best regards.

**Comment by jkhu29** [comment]
We have explained how to use pre-trained models for testing in the README.md. Please follow:

```shell
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 29501 firing_num.py -c /the/path/of/conf --model sdt --spike-mode lif --resume /the/path/of/parameters --no-resume-opt
```
