### ISSUE TITLE
environment version

### ISSUE THREAD

**Issue by ryikl** [BICLab/Spike-Driven-Transformer#13]
Hello, thank you for sharing. I would like to ask about your specific environment version, because when configuring the environment, it always shows that I do not have CuPy installed (but it is actually installed), so I guess it is a version problem.Or do you have any solution?

AssertionError: CuPy is not installed! You can install it from "https://github.com/cupy/cupy".

**Comment by jkhu29** [comment]
Please check previous issues https://github.com/BICLab/Spike-Driven-Transformer/issues/4 first.
