### ISSUE TITLE
github上的代码qkv生成部分和MLP生成部分用的是卷积，与论文描述不一致

### ISSUE THREAD

**Issue by xiaolongren969** [BICLab/Spike-Driven-Transformer#15]
![Snipaste_2024-10-18_11-14-26](https://github.com/user-attachments/assets/4bbc6402-f1d0-46f7-8ab6-eb2762f8a86d)
在代码中qkv生成部分和MLP生成部分用的是卷积，而在论文中示意图和表格能量计算部分用的是线性层的计算方式

**Comment by jkhu29** [comment]
Conv2d1x1与Linear层完全等价，具体原因请阅读pytorch docs或复习CS231n等深度学习基础课程。

**Comment by xiaolongren969** [comment]
好的，感想您的回复，我的问题解决了
