### ISSUE TITLE
我想请问一下论文里的table5所用到的网络结构参数是多少，是4-384还是GitHub库中的2-512

### ISSUE THREAD

**Issue by xiaolongren969** [BICLab/Spike-Driven-Transformer#16]
作者好，我想请问一下论文里的table5所用到的网络结构参数是多少，是4-384还是GitHub库中的2-512
![Snipaste_2024-10-20_18-29-31](https://github.com/user-attachments/assets/99b3a06d-d0d7-4feb-8231-a6aa17f66ef8)

**Comment by jkhu29** [comment]
2-512

**Comment by xiaolongren969** [comment]
好的，谢谢！
