### ISSUE TITLE
CIFAR architecture

### ISSUE THREAD

**Issue by Bobby-xb** [BICLab/Spike-Driven-Transformer#17]
您好，我与您的工作进行CIFAR结果对比时遇到了问题。我有翻到之前的issues提到，Table 5里面CIFAR的结果是2-512架构，请问Table 6的This work在同样的架构（2-512）下为什么性能和Table 5里不一样？

**Comment by jkhu29** [comment]
或许可以简单跑一下4-384和2-512的对比，时间有点过于久远了+我没在继续做这个方向，具体的settings可能记得不清楚。
- 按照这个[issue](https://github.com/BICLab/Spike-Driven-Transformer/issues/1)，当时我应该主要在2-512上进行的实验。
- 我没记错的话Table6的消融的时间步长是1。

**Comment by Bobby-xb** [comment]
明白了，谢谢
