### ISSUE TITLE
Virtual environment error

### ISSUE THREAD

**Issue by garasgaras** [BICLab/Spike-Driven-Transformer#2]
hello, I tried to install the virtual environment but got this error even though the cupy was installed. Is there a specific version of Cuda or Python?
Assert cupy is not None, 'CuPy is not installed! You can install it from "https://github.com/cupy/cupy".

**Comment by jkhu29** [comment]
Please follow the instructions in https://docs.cupy.dev/en/stable/install.html#installing-cupy-from-pypi to install cupy. Also, this error is related to [spikingjelly](https://github.com/fangwei123456/spikingjelly), please submit a related issue [here](https://github.com/fangwei123456/spikingjelly/issues), thank you.
