### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by yang-yk** [BICLab/Spike-Driven-Transformer#5]
Thanks for your excellent work. 
I tried Pytorch 1.10.0 and 1.12.0 when I ran the code. However, it shows that the version of pytorch is wrong. Can you tell me the specific Pytorch version? Many Thanks.

**Comment by jkhu29** [comment]
Please let me know your specific error message.

**Comment by BICLab** [comment]
Close this issue as there are no further questions, feel free to reopen it if you have more questions.
