### ISSUE TITLE
what device do you used in ImageNet？

### ISSUE THREAD

**Issue by 98ming** [BICLab/Spike-Driven-Transformer#8]
may I ask how long did you guys take to train thie model on ImageNet?

**Comment by jkhu29** [comment]
20min/ep when dim==512 & layer==8

**Comment by 98ming** [comment]
Thank you for your reply！
How many GPU did you use？And what is the name of the GPU？

**Comment by jkhu29** [comment]
> Thank you for your reply！ How many GPU did you use？And what is the name of the GPU？

8*A800

**Comment by 98ming** [comment]
Thanks，it's so cool!
